### ISSUE TITLE
v1.0.2 miss files

### ISSUE THREAD

**Issue by 7zxkv** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#1]
just for information, you didn't include the Config directory with version 1.0.2, which generates an error at runtime. If you use the directory from the previous version, there's no problem, you should replace the archive. 

Sincerely

**Comment by BackPonBeauty** [comment]
Hey, thanks for the feedback.

I replaced the config folder with the zip file I added.
Same as original supermodel3.
I expected to unzip it to the supermodel3 folder and use it.
It was incorrectly included in the first version.

Looks like I need to create a readme.txt.

thanks
