### ISSUE TITLE
Fix typos in the ticker in two games in the Sega Model 3 UI.

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#10]
![Снимок экрана (76)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/0f85573f-a738-4766-9634-4c094e697d7d)
![Снимок экрана (77)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/6d48e488-5cf3-40e5-bb74-bdadccb48f96)

**Comment by BackPonBeauty** [comment]
It's not a SegaModel3UI problem
Contact Supermodel3 official

![noob](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/58d8c41d-a4a0-4622-946f-ed5aeceb2a72)

**Comment by CCCP1982** [comment]
> It's not a SegaModel3UI problem Contact Supermodel3 official
> 
> ![noob](https://private-user-images.githubusercontent.com/107375174/313043615-58d8c41d-a4a0-4622-946f-ed5aeceb2a72.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODQ5NTcsIm5iZiI6MTcxMDQ4NDY1NywicGF0aCI6Ii8xMDczNzUxNzQvMzEzMDQzNjE1LTU4ZDhjNDFkLWE0YTAtNDYyMi05NDZmLWVkNWFlY2ViMmE3Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQwNjM3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjI5NjM2NGY1NGRkMjM5NDQ3ZmY3ZWFjZDc1ODkzYjZmYzBiMjllMDg0MWVmMWU3MTUxNDgyOGQ3NzAxNzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jQUzBR9B2q911THLsAloRRsDf7ui5ylN9T3b2jDo2to)


Yes, I assumed that the problem was in the emulator.
