### ISSUE TITLE
Update Games.xml

### ISSUE THREAD

**Issue by diegoginard** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#11]
Games.xml is outdated compared to the latest version of supermodel

**Comment by CCCP1982** [comment]
> Games.xml is outdated compared to the latest version of supermodel

do not copy

**Comment by CCCP1982** [comment]
Back On Beauty turn it off Games.xml )

**Comment by BackPonBeauty** [comment]
I completely forgot about this
Of course I'll fix it.
It will be fixed in the next version.
Binaries will be updated later.
thanks<3

PonMi💛
