### ISSUE TITLE
Contour

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#12]
Positioning is poorly visible in the background! Make fonts and outlines visible. Thanks

![Снимок экрана (88)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/fb2fc254-1c7d-4789-ba0a-8c1ea1c9c893)
![Снимок экрана (89)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/0b652324-b7f7-4161-bf9f-95c554a4b424)

**Comment by BackPonBeauty** [comment]
I thought you'd point out the problem with this.
Of course I fixed it. 
It will be applied in the next version.
Binaries will be updated later.

Thanks<3

ポン美💛

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/0cd50814-f4ed-4e42-8767-864866dbbf5a)

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/7baeb69b-777a-41cd-8f1a-9d4a10a93982)

**Comment by CCCP1982** [comment]
> I thought you'd point out the problem with this. Of course I fixed it. It will be applied in the next version. Binaries will be updated later.
> 
> Thanks<3
> 
> ポン美💛
> 
>   Thanks
