### ISSUE TITLE
games 62 roms

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#13]
You can add a function that shows how many novels have been scanned in the library. Here is an example

![Снимок экрана (90)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/26fd0c3d-1ed5-4cf3-ad2d-fddf37255a0f)

**Comment by BackPonBeauty** [comment]
It will be applied in the next version.
Binaries will be updated later.

![sss01](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/7dd63680-6b27-4473-b1b9-efa4f7ee48ba)

**Comment by CCCP1982** [comment]
> Это будет применено в следующей версии. Двоичные файлы будут обновлены позже.
> 

### SUPER  !!! thanks.

**Comment by CCCP1982** [comment]
> It will be applied in the next version. Binaries will be updated later.
> 

Fix it, ROM does not see, but writes 62).

![Снимок экрана (92)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/71b7a9dc-3d30-434a-85c3-3ec23c7d3a81)

**Comment by CCCP1982** [comment]
https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/00f3b832-f71a-42a0-8adb-00185c921484

**Comment by BackPonBeauty** [comment]
Are you testing me?

In conclusion, what is displayed there is the number of compatible games read from Game.xml.

You want to display the number of games you own, right?

Strictly speaking, what I'm creating is not a front end.
Yes, the relationship between MAME and MAME64 is different.
This is a launcher.

There are currently no plans to create a front end.

but

OK, this can be done with the code my 6 year old daughter drew.

My daughter says, "You can use the code."
I'll deal with it just this time.

It enumerates the file names in the Rom folder and compares them with the game names in Gamelist.
Showing the how many files founded.

I'll upload the binary only later.

I'm going to Universal Studios Japan with my 6-year-old daughter tomorrow.
Next time I'll upload a photo of her daughter.

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/266a043a-154e-4fa1-8472-fe57940d39a1)

PonMi💛💛💛

**Comment by CCCP1982** [comment]
Super !
