### ISSUE TITLE
SuperSampling  ARTIFACTS 

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#14]
I accidentally noticed an artifact: the place "SuperSampling" has perfectly changed to numbers.

https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/0ab87852-78b5-4c3e-8e70-ed2e86bf30a3

**Comment by BackPonBeauty** [comment]
aha

I didn't fix it.
rofl :)

**Comment by CCCP1982** [comment]
> aha
> 
> I didn't fix it. rofl :)

Super !!
