### ISSUE TITLE
SKIN

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#16]
Hello! Can I change the background of the interface skin? For example, you can change the color by clicking or in the interface above. Pink for other colors.

**Comment by BackPonBeauty** [comment]
It's also easy to change just the background color.
Label visibility may be affected by the color selected by the user.
You should also change the label color
Are the colors you choose cool, warm, dark, or light?
If I come up with a code to identify it, I'll let you know.

てゃんｋｓ
ポソ美

https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/8fe90674-c923-42d6-8ffd-ff0a50f61957

**Comment by CCCP1982** [comment]
> 
> てゃんｋｓ ポソ美
> 


Super 🤝

**Comment by CCCP1982** [comment]
> You should also change the label color Are the colors you choose cool, warm, dark, or light? 
> 
Any more you add the better

**Comment by BackPonBeauty** [comment]
Don't get me wrong
I have no plans to introduce a feature to change the background color in this application.

Please close

**Comment by BackPonBeauty** [comment]
I changed my mind
1.0.8.0

**Comment by CCCP1982** [comment]
> I changed my mind 1.0.8.0

Спасибо
