### ISSUE TITLE
Other minor issue...

### ISSUE THREAD

**Issue by Kimet1970** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#18]
A minor cosmetic issue is related to color in the "loading/sucsess" warning...
Won't be a more logic to set it with the same (selected) color of the GUI?
And a (heigh) centralized warning text...

Many thanks great work!!

There is the "same" Nuexx GUI Loader to System 2...
Do you think to do a System 2 version?

**Comment by BackPonBeauty** [comment]
Color issue fixed in 1.0.8.1

I don't know which emulator System 2 is pointing to
Are you talking about namco's System II?
Is it Capcom Play System 2 (CPS 2)?
Isn't it incorporated into M.A.M.E. (32/64)?

**Comment by BackPonBeauty** [comment]
Color issue fixed in 1.0.8.1

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/a6d515a3-4c0a-41be-a9b8-c8df02fef7d0)

I don't know which emulator System 2 is pointing to
Are you talking about namco's System II?
Is it Capcom Play System 2 (CPS 2)?
Isn't it incorporated into M.A.M.E. (32/64)?

**Comment by CCCP1982** [comment]
> 
> There is the "same" Nuexx GUI Loader to System 2... Do you think to do a System 2 version?

Dear, this is the interface for MODEL 3 games!

**Comment by CCCP1982** [comment]
> Dear, this is the interface for MODEL 3 games!

Dear, this is the interface for MODEL 3 games!

**Comment by Kimet1970** [comment]
> > Dear, this is the interface for MODEL 3 games!
> 
> Dear, this is the interface for MODEL 3 games!

Little Princess...
Putin didn't recruit you to steal the land from the Ukrainian people?

**Comment by CCCP1982** [comment]
> > > Dear, this is the interface for MODEL 3 games!
> > 
> > 
> > Dear, this is the interface for MODEL 3 games!
> 
> Little Princess... Putin didn't recruit you to steal the land from the Ukrainian people?

YOU'RE A STUPID MAN! POLITICS HAS NOTHING TO DO WITH IT!

**Comment by Kimet1970** [comment]
> > > > Dear, this is the interface for MODEL 3 games!
> > 
> > 
> > Little Princess... Putin didn't recruit you to steal the land from the Ukrainian people?
> 
> YOU'RE A STUPID MAN! POLITICS HAS NOTHING TO DO WITH IT!

Yes! Because young Russian boys are dying too! But we lost patience after see a big kid say that the interface is for system 3 (three times!)...
If one day the author makes it to System 2, it will be good for everyone who uses this system!
Behave like an adult...

**Comment by BackPonBeauty** [comment]
It looks like the download link is broken.
So I can't verify it.
Please give it to me in secret.
Is there a problem with SegaModel2UI created by Nuexzz?

Please clarify the reason for creating a new one.

Please refrain from slandering others or discussing political ideas.

Love, Peace and Ponmi💛

**Comment by Kimet1970** [comment]
> It looks like the download link is broken. So I can't verify it. Please give it to me in secret. Is there a problem with SegaModel2UI created by Nuexzz?
> 
> Please clarify the reason for creating a new one.
> 
> Please refrain from slandering others or discussing political ideas.

Actually there is no problem...
In fact Nuexx Sega-Model-3-UI was working fine to me too...
But You are introducing improvements to program... and (apparently) they are very similar...
Maybe would you like to see the other loader...
How can I  to send it for you??
Do you have an e-mail?

**Comment by BackPonBeauty** [comment]
I don't have time.
Please close it as it is not related to this project.
Please send a private message if necessary.
