### ISSUE TITLE
Let us edit / add parameters on running a rom on supermodel.exe

### ISSUE THREAD

**Issue by stefanpausch** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#19]
I would love to show/add/alter the parameters on supermodel.exe on specific games.

f.e. i want to use the FFBPlugin which adds Forcefeedback to more gamesss, but those require the option "-outputs=win"

**Comment by BackPonBeauty** [comment]
Hello
I didn't know about the existence of -output = win.
Start by examining what the command can do.
I would consider the ability to add command options.

Thanks

PonMi

**Comment by BackPonBeauty** [comment]
1.1.0.2

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/a7392dde-d7d3-42ee-a506-21f894e15ba8)

**Comment by BackPonBeauty** [comment]
"-outputs=win" Is this command option required in the latest Supermodel 3?
Wouldn't force feedback emulation just require the drive board ROM to be present in the ZIP file?
