### ISSUE TITLE
ROMs directory can't have spaces

### ISSUE THREAD

**Issue by DonelBueno** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#2]
If there is a space on the adress for the ROMs folder (maybe on the previous folders too), the games fail to load.

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/4239694/60976aa3-5462-45b6-b960-3d6a7df3bbda)
![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/4239694/dd65bb59-cd71-4bfa-8011-3a222b037698)

Also, is there a way to sort the games list by alphabetical order?

**Comment by BackPonBeauty** [comment]
You are certainly right. Confirmed.

and fixed it

Fixed an issue with specifying the rom folder path.
The Refreshrate item only reads and writes the ini file, so
I tried adding a checkbox for True-hz.
It will be 1.0.3.
I'll upload the binaries later.

**Comment by BackPonBeauty** [comment]
Hi hello
It is possible to sort the game list.
I intentionally made it unsortable.
We will look into a better direction.
