### ISSUE TITLE
Default size of the UI window is too large on crt monitor

### ISSUE THREAD

**Issue by stefanpausch** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#20]
I am using an old VGA-Capable CRT which only supports the resolution of 854x480 - The UI window is too large for that resolution

- let us resize the window / add scrollbars to it (and remember the size)
- optional: let us move the window to another attached secondary monitor. For some reasons window+cursor-keys don't respond on the ui window

thanks a lot!

**Comment by BackPonBeauty** [comment]
Hello
Thank you for your opinion
I was concerned that the form size would protrude if the resolution was low.
To solve this problem, I think it is necessary to launch a new SegaModel3UI tiny (tentative name) project.

I'm making plans.

thank you

PonMiiiiiiiiiiiii
