### ISSUE TITLE
Disable fake scanlines per default! 

### ISSUE THREAD

**Issue by stefanpausch** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#21]
Please let us disable fake scan lines per default! or let me know how to get rid of the feature.

If i run the UI and put the window into the background (f.e. for writing this feature request/bug report) the scanline window pops up on half my screen for some strange reasons...

**Comment by BackPonBeauty** [comment]
Hello
The next modification will add Scanline on/off functionality.

thank you

Ponmi

**Comment by leoxxx** [comment]
How to disable the key for fake scan lines? I set "S" to down.

**Comment by leoxxx** [comment]
You can use 1.0.9.0 before new release upload.
