### ISSUE TITLE
x64 exe

### ISSUE THREAD

**Issue by leoxxx** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#22]
Please build x64 exe.

**Comment by BackPonBeauty** [comment]
Please provide a clear reason for building on x64.
Are you having any issues with x86 build?

**Comment by leoxxx** [comment]
No. I think x64 will be run better on x64-bit system. And Supermodel have only a win64 build.

**Comment by BackPonBeauty** [comment]
SegaModel3UI doesn't require high performance and doesn't use a lot of memory, so I don't feel the need for an x64 build.

Typically, x64 builds are not run directly in an x86 environment. An x64 build refers to a program compiled for a 64-bit architecture, while an x86 environment is based on a 32-bit architecture. Therefore, programs built on x64 must run in an environment that supports 64-bit architectures.

However, some 64-bit Windows systems offer a compatibility layer called Wow64 that allows them to run 32-bit applications. Therefore, programs built on x64 can run in 32-bit mode on a 64-bit Windows system, but cannot run directly in an x86 environment.

**Comment by Kimet1970** [comment]
I think there is no sense to speak about performance issues related to SegaModel3UI...
It's only a graphical interface... Only program that loads the emulator...
If your emulator is 64 bits... there is no performance issues...
Or am I wrong?

**Comment by CCCP1982** [comment]
> I think there is no sense to speak about performance issues related to SegaModel3UI... It's only a graphical interface... Only program that loads the emulator... If your emulator is 64 bits... there is no performance issues... Or am I wrong?
emulator 64 bits

**Comment by BackPonBeauty** [comment]
SegaModel3UI is not a front end.
Supermodel.exe is not installed internally.
This is a launcher.
It does not affect the performance of supermodel startup or execution speed.

Supermodel3UIfor20240128+ is open source.
You may be able to compile and verify the x64 build yourself.

Pablo Diego José Francisco de Paula Juan Nepomuceno María de los Remedios Cipriano de la Santísima Trinidad Ruiz y PonMi💛
