### ISSUE TITLE
1.1.0.3

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#23]
It does not save. 
GamepadViwe
FakeScanLine

https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/840fea20-d1f8-4833-8ca2-895ded02fb3e

**Comment by BackPonBeauty** [comment]
That's because you decided not to save those items.
Why should you save those items?

**Comment by CCCP1982** [comment]
> That's because I decided not to save those items. Why should you save those items?

To avoid turning it on all the time.

**Comment by ner00** [comment]
@BackPonBeauty You could implement a dedicated ini file for these and other exclusive GUI options.
The first time you launch the GUI, the S hotkey never works, you must always enable it in the GUI, and I understand that, but would be useful to remember the state and avoid the user forgetting and having to quit the game and enable every time. Not a big deal, but would be a slight improvement in my view.

**Comment by Kimet1970** [comment]
> It does not save. GamepadViwe FakeScanLine
> 
>  bandicam.2024-03-27.16-52-21-125.mp4

URSS1982,
You can create a new branch for MODEL 3 with saving GamepadViwe and Fake ScanLine and Improve and update the SEGA MODEL 3UI!

zip-errors )

Best regards!!

**Comment by BackPonBeauty** [comment]
fixed next release 
thanks

**Comment by ner00** [comment]
@CCCP1982 You should not close the issue immediately, until it is implemented. Open issues also serve the purpose of helping the developer managing the project features and priorities.

**Comment by CCCP1982** [comment]
> @CCCP1982 Не следует закрывать выпуск немедленно, пока он не будет реализован. Открытые выпуски также служат для того, чтобы помочь разработчику управлять функциями и приоритетами проекта.
It's working, I've closed it.

**Comment by ner00** [comment]
My mistake, I didn't notice that the developer was using the same release post for all updates. When I saw "Last week" I didn't think it was updated yet.
![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/2269603/53c4b86e-a6ef-4c11-9ca5-a6f688f9bb46)
