### ISSUE TITLE
ScanLine overlay does not close after quitting the game

### ISSUE THREAD

**Issue by ner00** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#24]
As you can see from the screenshot at the bottom, after quitting the emulator with the Esc key, the ScanLine overlay thread stays present. I understand that this would probably require the GUI to monitor the emulator process running and may not be desirable. I just thought to raise the issue to see what you think about this possibility. 

There is an alternative workaround that should be easier to implement, make the Esc also a hotkey to disable scanlines. Even though that won't solve the issue for people that close the emulator with the mouse or Alt+F4, or whatever, but would work reasonably for most others which use the Esc key to close a game.

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/2269603/e6a6b34f-28f2-4a8f-b26f-340120f93ad5)

**Comment by BackPonBeauty** [comment]
Actually, I don't know if the fake scan line feature is well received or not. This may not be a necessary feature for some people.

I'm thinking of making the fake scan line feature standalone.

A fix has been made.
It does not work properly when multiple supermodels are started (link-play).

**Comment by BackPonBeauty** [comment]
ah
1.1.0.5 has an issue where fake-scanline cannot be used with other emulators.

Is the following correct?
"I want to use it with other emulators, but I want the scan line to disappear when I press the esc key while the supermodel is running."

automatic translation

**Comment by ner00** [comment]
>Actually, I don't know if the fake scan line feature is well received or not. This may not be a necessary feature for some people.

I really like this feature, I use it in every emulator that supports some kind of shader or overlay that mimics old monitors, that way the image and "unpolished" looks seems more retro and less jarring. Although some people may not care for it - one example is people who use the emulator with real CRT monitors.

>Is the following correct?
>"I want to use it with other emulators, but I want the scan line to disappear when I press the esc key while the supermodel is running."

Personally, no. This was not what I meant.
I **do not** want to use it with other emulators, I want the scan line to disappear when I press the esc key to exit supermodel. There is a generic tool to simulate scanlines, it is named ShaderGlass, but I do not use it since most emulators have some support for scanlines.

Your solution for supermodel is good enough in my opinion. I just want the fake scanlines to disappear when I close supermodel with Esc key.

**Comment by BackPonBeauty** [comment]
The behavior of 1.1.0.5 is as follows.
When fake-scanline is enabled, global key hooks are enabled. (Global key hook is a function that accepts keyboard input no matter which window has focus.)
If the global key hook is enabled but there is no supermodel process, pressing the S key will not display false scanlines.
If you have a supermodel process, the S key will make pseudo scan lines appear and disappear.
fake-scanline constantly monitors whether a supermodel process exists.
If no supermodel process is found, the fake-scanline disappears. Global key hooks remain enabled.

Is this the behavior you're looking for?
This changed in 1.1.0.5.

**Comment by ner00** [comment]
Yes, this is perfect!
Thank you.
