### ISSUE TITLE
Font color should not affect button with [...]

### ISSUE THREAD

**Issue by ner00** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#25]
![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/2269603/e1aa4052-c28b-400e-9b91-9ca1f28459e6)

If the font is white, you can barely see the 3 dots of the last button, on the right. Like the resolution combobox, and all other buttons in the GUI, their font color should not change. This is a very picky issue, but something that should be easily fixable for a future release.

**Comment by BackPonBeauty** [comment]
fix next release

thanks

**Comment by ner00** [comment]
I see this is also fixed now in v1.1.0.5
