### ISSUE TITLE
No Fake Scan Lines

### ISSUE THREAD

**Issue by TTurbo23** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#29]
Hi there,

I've tested the enabling fake scanlines and it doesn't seem to do anything when enabled. Is this feature broken? The config file reflects the change from the interface, so it's definitely turned on.

Thanks.

**Comment by CCCP1982** [comment]
> Hi there,
> 
> I've tested the enabling fake scanlines and it doesn't seem to do anything when enabled. Is this feature broken? The config file reflects the change from the interface, so it's definitely turned on.
> 
> Thanks.

Only in full-screen mode!

**Comment by BackPonBeauty** [comment]
Please show me something to prove.
Please explain what steps you took.
Please also tell me the usage environment.

**Comment by TTurbo23** [comment]
I downloaded the update and it said how to enable scanlines on the UI, ctrl+S, so that works. It only works in a windowed mode, is that correct?

I didn't read the read me file, so was this info in there too?

Thanks,
Terry.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BackPonBeauty** [comment]
I haven't read the details of this issue.
I don't think this is an issue.
I don't know.

私はこの 問題の内容は読んでない。
これは問題ではないと思う。
しらんけど。
