### ISSUE TITLE
3D Legacy  

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#3]
In Legacy mode, it does not start the game.

**Comment by BackPonBeauty** [comment]
Hi hello

Is my understanding that "Legacy mode is New3DEngine = False" correct? .
I can't reproduce the problem of not starting in Legacy mode.

Can you think of other causes?
I don't understand why there is no information about your environment.

![legacy](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/a2ae96b5-771f-4c52-ae5b-38a770544ca0)

**Comment by CCCP1982** [comment]
The Sega Model 3 UI -r886 runs games, but your SM3UI_ver1.0.2 does not.
![Снимок экрана (39)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/c0f83ade-9f52-4452-8792-55dbe80f1174)
![Снимок экрана (40)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/d5185622-7046-46fa-9847-b3698a870013)

**Comment by DonelBueno** [comment]
Try 1.03. It's probably the space issue I reported earlier. Make sure to redefine your ROMs directory.

**Comment by BackPonBeauty** [comment]
Hello
Thank you for your report.
Investigate the issue.

I'm not good at English, so I'm sorry if my words are rude.

**Comment by CCCP1982** [comment]
> Попробуйте 1.03. Вероятно, это проблема с пространством, о которой я сообщал ранее. Обязательно переопределите каталог ваших ROM.
that's right, thank you

**Comment by CCCP1982** [comment]
> Try 1.03. It's probably the space issue I reported earlier. Make sure to redefine your ROMs directory.

that's right, thank you

**Comment by CCCP1982** [comment]
> Hello Thank you for your report. Investigate the issue.
> 
> I'm not good at English, so I'm sorry if my words are rude.
Interface SM3UI ver1.0.3 on the old 3D Legacy engine has been fixed!
Thank you my friend .
![Снимок экрана (42)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/cb683f01-1a26-4d86-98aa-7f2d6187e961)
