### ISSUE TITLE
Title Bar says 1.1.0.7

### ISSUE THREAD

**Issue by manic232** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#33]
When running 1.1.0.8 the title bar says 1.1.0.7, just checking as this might just be a case of the wrong version being typed, but seeing as there is this important issue with 11.0.7 I just wanted to make sure that the wrong version was not downloading.

**Comment by BackPonBeauty** [comment]
Hello
Thanks for letting me know
It seems I uploaded the wrong file.
Maybe I had too much to drink.

I replaced the release file with 1.1.0.8.

Thanks

**Comment by manic232** [comment]
No problem, thanks for replying and re uploading so quickly.
