### ISSUE TITLE
Request for Supsampling removal option

### ISSUE THREAD

**Issue by WarpedPolygon** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#34]
Excellent updates mate. Really appreciate making everything soo much more accessible. 

Can I request an option to remove supersampling for mostly performance reasons? 

I'm aware it has no 0 value as it won't display an image when set to 0, so I know that route isn't available. 

To include the option in the UI at all requires it to be set to at least 1. 
For supersampling to not be used at all, the option needs to be removed from the ini entirely.

Is there a way to 'toggle' if supersampling is included in the ini file? Like a Supersampling On/Off that includes or excludes it from the ini.

Supersampling is pretty heavy on performance and can introduce some interesting artifacting for some games. Would be awesome to exclude it from those games.

**Comment by BackPonBeauty** [comment]
Hello
Thank you for your suggestion.

If deleting the key from the ini file completely disables supersampling, then it should be deleted.

Let's add a checkbox to SuperSampling.
The ini file will be rewritten when the checkbox is checked/unchecked.

Please check the release file.
ver1.1.0.9

**Comment by WarpedPolygon** [comment]
Well that was fast AF. Thanks man, you are a gentleman & a squire.
