### ISSUE TITLE
List of favorite games

### ISSUE THREAD

**Issue by dante3732** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#36]
Please add the ability to display only some games, not the entire list.

**Comment by BackPonBeauty** [comment]
Thank you for your idea.

I think it's not that difficult to implement this function.

But sorry.

Right now I have other projects and can't think about implementing this function.

Please give me some time.

Thank you

PonMi(@headache)

**Comment by BackPonBeauty** [comment]
Check 
https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/releases

**Comment by dante3732** [comment]
> Check https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/releases

It work great!
![image](https://github.com/user-attachments/assets/b2e9e748-0e39-46e4-b711-bff22666803b)

**Comment by D-an-W** [comment]
Excellent addition 👍🏻

**Comment by dante3732** [comment]
By the way, could you please add the same feature to the GUI for the Sega Model 2 or have you completely abandoned it?

**Comment by BackPonBeauty** [comment]
Hey there.

I haven't forgotten about Model2, my friend.

I'll start with the research.

It's a low priority for me right now.

I have so many projects.

But I haven't forgotten.

Thanks

PonMi(@Gunslinger)

**Comment by BackPonBeauty** [comment]
I looked into model2 emu,
but a launcher already exists, why create a new one?
![image](https://github.com/user-attachments/assets/e2778fd4-8092-44b5-a73c-9fec95e79fca)

**Comment by dante3732** [comment]
> I looked into model2 emu,
> but a launcher already exists, why create a new one?

Aren't you the creator of it? I was referring to the favorites list in the launcher.
