### ISSUE TITLE
A selection of games inspired by various logos.

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#4]
I want to share with you a selection of logo games.

It would be great if you could add some logs to the interface. I can provide game logs (screenshots) in zip files.

Thank you for working to improve the interface of SUPERMODE3 emulator.

**Comment by CCCP1982** [comment]
> Hey, hey, hey Hello
> 
> I downloaded the file I'll use it when I make a new version. thank you.
> 
> And I will complete it with 1.0.4. I will respond to any critical issues or changes to Supermodel 3.
> 
> Let's meet again


おかげで写真はあなたの裁量で適用することができます。

**Comment by BackPonBeauty** [comment]
You can replace the image files in the snaps folder.
It will be applied if you use the same name as the ROM image.

thank you.

**Comment by CCCP1982** [comment]
Not all photos can be replaced.
Would you like to organize a normal photo gallery for you personally? if not, I will close the repository.

**Comment by CCCP1982** [comment]
> You can replace the image files in the snaps folder. t will be applied if you use the same name as the ROM image.
> 
> thank you.
> 

Can I do it or not? My friend.

![Снимок экрана (54)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/63e476b6-85fb-4822-80f5-fb61028596c1)
![Снимок экрана (55)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/6e78dc89-bb67-4430-be79-1af748cb045f)
