### ISSUE TITLE
Noise from UI App when InputGearShift is used

### ISSUE THREAD

**Issue by Milonet2k** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#46]
Hi BackPonBeauty,
I have been using your software recently, thanks for making it!

Just now I finally got a bit further getting my wheel and shifter to work.
They both work finally but when I use the shifter I get a weird sound playing.
There is also a weird sound when the UI app starts up - which I thought was my wife shouting!
Do you know about this and is there a way to stop the UI app from making noise?

Best regards and thanks again,
Milo

**Comment by BackPonBeauty** [comment]
In the latest release(Dec 14 2024), your wife won't scream, and I don't think my ex-wife screams either. A button with a ♪ mark has been added. It is disabled by default. This setting is not saved.
Disable Xinputviewer or press the ♪ mark to disable it.

thanks 
PonMi

**Comment by Milonet2k** [comment]
Now I understand..
I guessed Xinputviewer was to help the app receive xinput before when I first started.
I deleted the audio files in the mean time & nearly no more wife as I accused her of screeching lol.

If I could be very very cheeky please could you add a check box for the '***FFB Arcade Plugin***'?
I am kind of thinking though the 'problem' with the force feedback being activated after being on the grass (until a car replacement?) is actually original in the cabinet & it does that..? I seem to remember it as a kid..!

Cheers,
Milo




________________________________

**Comment by BackPonBeauty** [comment]
[Ver1.1.1.6](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/releases/tag/Segamodel3UIver1116)

The UI already supports the FFB plugin.
Just check ForceFeedback in the Controls tab.
You will need the [FFBArcadePlugin](https://github.com/Boomslangnz/FFBArcadePlugin)

![image](https://github.com/user-attachments/assets/dfc3124e-5c0f-44f0-8f68-bdbb22988102)

My ex-wives left me.
Four of them.
I realized I wasn't cut out for married life.

If you are satisfied, please close this issue.

PonMi(★)

**Comment by Milonet2k** [comment]
Thank you!
