### ISSUE TITLE
Step

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#5]
Is it possible to add a visible part of the Step string? Can I move the division?

Yes, I know, you can click on the bottom slider, but it's inconvenient.

![Снимок экрана (45)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/80e5bee0-a72f-4380-b72c-6b7ba5fcf035)

**Comment by CCCP1982** [comment]
> А, привет
> 
> Я думаю, что сетка списка игр смещена из-за разницы в ОС, Windows 10 или 11.
> 
> Разработка и проверка выполняются в Windows 11.
> 
> Я проведу небольшое исследование по проверке, но я занят в реальной жизни, поэтому, пожалуйста, уделите мне немного времени.
> 
> Спасибо
> 

I have Windows 10 
Thanks .

**Comment by CCCP1982** [comment]
> Ah, hello
> 
> I think the game list grid is misaligned due to the difference in OS, Windows 10 or 11.
> 
> Development and verification are performed on Windows 11.
> 
> I'll do some verification research, but I'm busy in real life, so please give me some time.
> 
> thanks

I have Windows 10 
Thanks .

**Comment by CCCP1982** [comment]
> Ah, hello
> 
> I think the game list grid is misaligned due to the difference in OS, Windows 10 or 11.
> 
> Development and verification are performed on Windows 11.
> 
> I'll do some verification research, but I'm busy in real life, so please give me some time.
> 
> thanks
> 
You can use mouse stretching as an option. )

![Снимок экрана (45)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/8a874bcd-f799-4904-b4c0-886635cb886a)

**Comment by BackPonBeauty** [comment]
In version 1.0.5, Columns of gamelist can be changed.
The settings are then written to the ini file.

It's technically possible to stretch the size of the foam, but it's not possible because it creates other problems.

thank you.

**Comment by CCCP1982** [comment]
> In version 1.0.5, Columns of gamelist can be changed. The settings are then written to the ini file.
> 
> It's technically possible to stretch the size of the foam, but it's not possible because it creates other problems.
> 
> thank you.

Everything is working, thank you.
![Снимок экрана (50)](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/21f049ee-2534-4f63-9b5f-b3afb229870e)
