### ISSUE TITLE
Problem with bigger font sizes...

### ISSUE THREAD

**Issue by Kimet1970** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#6]
The Loader is good!! And now the path issue is fixes, it working fine.
But there is a cosmectic question related to font size... I use the Windows "Medium" texts (in Windows 7) and the GUI doesn't have a automatic rescale... See the pictures!
Many thanks!!!
Great work!!
![image_2024-03-13_151625658](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/82340648/13ab181a-2530-4fcb-89c5-c1ebc0fcfa17)
![image_2024-03-13_151755932](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/82340648/64983d0f-ba54-44aa-a75c-c3932ab83997)

**Comment by BackPonBeauty** [comment]
Lack of knowledge about high DPI environments and scaling.
Windows7 is WindowsXP format or something

Sorry, I cannot respond.

![0001](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/856cbbc9-4ff9-4062-9985-f7d55bf7065f)
![0002](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/8eb639cf-addd-43e8-8698-44a62d55da8e)

**Comment by CCCP1982** [comment]
We need to switch to Windows 10 , 11 .
Windows 7 is 14 years old!

**Comment by CCCP1982** [comment]
> The Loader is good!! And now the path issue is fixes, it working fine. But there is a cosmectic question related to font size... I use the Windows "Medium" texts (in Windows 7) and the GUI doesn't have a automatic rescale... See the pictures! Many thanks!!! 

We need to switch to Windows 10 , 11 .
Windows 7 is 14 years old!

**Comment by Kimet1970** [comment]
> > The Loader is good!! And now the path issue is fixes, it working fine. But there is a cosmectic question related to font size... I use the Windows "Medium" texts (in Windows 7) and the GUI doesn't have a automatic rescale... See the pictures! Many thanks!!!
> 
> We need to switch to Windows 10 , 11 . Windows 7 is 14 years old!

I have computers with Windows 10 and 11... to use X-Plane 12 and other... But why would I exchange a very good system for one that is rubbish? Made for computer novices?

**Comment by BackPonBeauty** [comment]
I thought of my own answer
I tried making it possible to change the fontsize.
please test it

If there are no problems, I will release it as the next version.

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/72c841a6-1472-4894-bae2-daaadbdaf0bf)


[SM3UI_ver Alpha.zip](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/files/14613635/SM3UI_ver.Alpha.zip)

**Comment by BackPonBeauty** [comment]
I thought of my own answer
I tried making it possible to change the Font size.
please test it

If there are no problems, I will release it as the next version.

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/15e7f556-4c3f-401d-8dbe-7ba40036616d)

[SM3UI_ver Alpha.zip](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/files/14613786/SM3UI_ver.Alpha.zip)

**Comment by Kimet1970** [comment]
Thank you!!
It'sworking fine!! Except the "About" tab (not included in customizeable fonts).
The font 6 is very little!
Maybe 8, 10 and 12 fonts or even 8, 10, 12, 14...
Many thanks!!!!

**Comment by BackPonBeauty** [comment]
In the next version, the font sizes that can be set will only be Normal (10) and Small (8). 
Binaries will be updated later.
Fixed the About window as well.

thanks

ポン美💛
![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/c68d4b44-91f7-4ebf-9e32-f34028c871f8)
