### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by CCCP1982** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#7]
You sort it yourself, but it doesn't save it automatically... Can I do it?

Download the video.

https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/142115581/b35167da-d704-4233-8fbf-975e4cf91594

**Comment by BackPonBeauty** [comment]
Check 1.0.6

It was quite forced, but I got it to work.
Source code becomes spaghetti
It also remembers the last game you selected.
I've tried maintaining selected rows when sorting but it's difficult.

Let's meet again

Ponmi

Don't test me!

俺を試すのはやめろ！
ふざけんな！

冗談だよ💛
