### ISSUE TITLE
MultiThreded - Typo

### ISSUE THREAD

**Issue by PolybiusExtreme** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#8]
There is a typo in the UI. MultiThreded needs to changed to MultiThreaded.

**Comment by BackPonBeauty** [comment]
Thank you for your report.
It will be fixed in next version

![image](https://github.com/BackPonBeauty/Sega-Model-3-UI-for-20240128-/assets/107375174/95527616-ffa1-4e54-b54a-4968de416c4f)

thanks
PonMi
