### ISSUE TITLE
Romset

### ISSUE THREAD

**Issue by AngryScotsmanGaming** [BackPonBeauty/Sega-Model-3-UI-for-20240128-#9]
Hi love the work you're doing upgrading the frontend but I noticed that the romset used for the older models no longer work...

So what mame version set is this using (I mean number wise) as I tried the latest split, non merged and merged and can only get the parent games to work

**Comment by CCCP1982** [comment]
> Hi love the work you're doing upgrading the frontend but I noticed that the romset used for the older models no longer work...
> 
> So what mame version set is this using (I mean number wise) as I tried the latest split, non merged and merged and can only get the parent games to work

All 62 roms should work correctly with MAME 252 .

**Comment by BackPonBeauty** [comment]
It's not a Supermodel3UI issue
Ask your question on the official Supermodel 3 forum

**Comment by AngryScotsmanGaming** [comment]
> It's not a SegaModel3UI issue Ask your question on the official Supermodel 3 forum

Strange as i said rom set was fine till I used your upgrade but will check with them..........

Thanks for getting back to me

**Comment by BackPonBeauty** [comment]
I think this issue is a ROM set problem.
This seems to be showing the parent ROM set.

in,
Please close it as it has nothing to do with SegaModel3UI.
